# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='resource/digits.proto',
  package='',
  serialized_pb='\n\x15resource/digits.proto\"&\n\x05\x44igit\x12\x0f\n\x07numeral\x18\x01 \x02(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\"A\n\x08\x46\x65\x61tures\x12\x0f\n\x07numeral\x18\x01 \x02(\r\x12\x11\n\tx_feature\x18\x02 \x02(\x01\x12\x11\n\ty_feature\x18\x03 \x02(\x01\"\x1a\n\x07Weights\x12\x0f\n\x07weights\x18\x01 \x03(\x02\"\x81\x01\n\x08PlotData\x12\x1c\n\x04type\x18\x01 \x02(\x0e\x32\x0e.PlotData.Type\x12\x18\n\x05point\x18\x02 \x01(\x0b\x32\t.Features\x12\x16\n\x04line\x18\x03 \x01(\x0b\x32\x08.Weights\"%\n\x04Type\x12\x0e\n\npoint_type\x10\x01\x12\r\n\tline_type\x10\x02')



_PLOTDATA_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='PlotData.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='point_type', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='line_type', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=253,
  serialized_end=290,
)


_DIGIT = descriptor.Descriptor(
  name='Digit',
  full_name='Digit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='numeral', full_name='Digit.numeral', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='Digit.data', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=63,
)


_FEATURES = descriptor.Descriptor(
  name='Features',
  full_name='Features',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='numeral', full_name='Features.numeral', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='x_feature', full_name='Features.x_feature', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y_feature', full_name='Features.y_feature', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=65,
  serialized_end=130,
)


_WEIGHTS = descriptor.Descriptor(
  name='Weights',
  full_name='Weights',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='weights', full_name='Weights.weights', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=132,
  serialized_end=158,
)


_PLOTDATA = descriptor.Descriptor(
  name='PlotData',
  full_name='PlotData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='PlotData.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='point', full_name='PlotData.point', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='line', full_name='PlotData.line', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PLOTDATA_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=161,
  serialized_end=290,
)

_PLOTDATA.fields_by_name['type'].enum_type = _PLOTDATA_TYPE
_PLOTDATA.fields_by_name['point'].message_type = _FEATURES
_PLOTDATA.fields_by_name['line'].message_type = _WEIGHTS
_PLOTDATA_TYPE.containing_type = _PLOTDATA;
DESCRIPTOR.message_types_by_name['Digit'] = _DIGIT
DESCRIPTOR.message_types_by_name['Features'] = _FEATURES
DESCRIPTOR.message_types_by_name['Weights'] = _WEIGHTS
DESCRIPTOR.message_types_by_name['PlotData'] = _PLOTDATA

class Digit(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DIGIT
  
  # @@protoc_insertion_point(class_scope:Digit)

class Features(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FEATURES
  
  # @@protoc_insertion_point(class_scope:Features)

class Weights(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WEIGHTS
  
  # @@protoc_insertion_point(class_scope:Weights)

class PlotData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLOTDATA
  
  # @@protoc_insertion_point(class_scope:PlotData)

# @@protoc_insertion_point(module_scope)
